[package]
name = "tetetris"
version = "1.0.0"
edition = "2018"
description = "TeTetris is a terminal tetris game"
readme = "README.md"
authors = ["Alice Rum <wyvie@wyvie.org>"]


[dependencies]
tui = "0.16"
termion = "1.5"
clap = "2.33.3"
rand = "0.8.4"
